name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
      env:
        GO111MODULE: on

    - name: Run coverage
      run: go test -coverprofile=coverage.txt -covermode=atomic -timeout 40m -v ./...
      env:
        GO111MODULE: on
        
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
