name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: go build -v ./...
      env:
        GO111MODULE: on

    - name: Run coverage
      run: go test -coverprofile=coverage.txt -covermode=atomic -timeout 40m -v ./...
      env:
        GO111MODULE: on
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.txt
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
